version: "3.8"
services:
  api:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        development: "True"
    restart: on-failure
    ports:
      - "${FLASK_RUN_PORT}:8001"
    command: "pipenv run flask run --host=${FLASK_RUN_HOST} --port=8001"
    networks:
      - kafka
    depends_on:
      - db
    env_file:
      - .env
      - .secrets.env
    volumes:
      - ./src/bookstore.log:/bookstore.log
      - ./src/bookstore_errors.log:/bookstore_errors.log
      - ./src/publication_data.log:/publication_data.log
  db:
    image: postgres:11.8
    container_name: "bookstore_database"
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    command: [ "postgres", "-c", "wal_level=logical" ]
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./deploy/postgres/local_db/init.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - .env
      - .secrets.env
    networks:
      - kafka

networks:
  kafka:
    external: true
    name: kafka

volumes:
  postgres_data:
